// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0ddniHirenCm3dOUQy-7g3oek3UbTSs',
    appId: '1:1086290714163:web:9dc666e9b6581bc9aa0d46',
    messagingSenderId: '1086290714163',
    projectId: 'medical-app-f52d5',
    authDomain: 'medical-app-f52d5.firebaseapp.com',
    storageBucket: 'medical-app-f52d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArL3OBhC4bAtbvbccJk5zJOtQ6WFk4iDY',
    appId: '1:1086290714163:android:949377c5efe8cfc0aa0d46',
    messagingSenderId: '1086290714163',
    projectId: 'medical-app-f52d5',
    storageBucket: 'medical-app-f52d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsKZFtY3vMxsj3wJDTgfnYmwWg7XQTik',
    appId: '1:1086290714163:ios:48636df6fbf8f093aa0d46',
    messagingSenderId: '1086290714163',
    projectId: 'medical-app-f52d5',
    storageBucket: 'medical-app-f52d5.appspot.com',
    iosClientId: '1086290714163-3hjk4kqqvf4fmhqbraiqmf8m6itmni6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQsKZFtY3vMxsj3wJDTgfnYmwWg7XQTik',
    appId: '1:1086290714163:ios:48636df6fbf8f093aa0d46',
    messagingSenderId: '1086290714163',
    projectId: 'medical-app-f52d5',
    storageBucket: 'medical-app-f52d5.appspot.com',
    iosClientId: '1086290714163-3hjk4kqqvf4fmhqbraiqmf8m6itmni6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalApp',
  );
}
